Fix contract sent with reqHistoricalTicks
stoqey/ib pull request #88
Opened 2021-06-04 16:02 UTC by ant-fx

Proposed fix for the issue mentioned in https://github.com/stoqey/ib/issues/86.

I'm not 100% sure what's going on with IB's contract format, looking at their Python api they seem to send different data depending on the function call.

The update here uses the Python api as a reference and has a test. The test will only run if you have the required market subscription unfortunately :(

```python
flds += [make_field(OUT.REQ_HISTORICAL_TICKS),
         make_field(reqId),
         make_field(contract.conId),
         make_field(contract.symbol),
         make_field(contract.secType),
         make_field(contract.lastTradeDateOrContractMonth),
         make_field(contract.strike),
         make_field(contract.right),
         make_field(contract.multiplier),
         make_field(contract.exchange),
         make_field(contract.primaryExchange),
         make_field(contract.currency),
         make_field(contract.localSymbol),
         make_field(contract.tradingClass),
         make_field(contract.includeExpired),
         make_field(startDateTime),
         make_field(endDateTime),
         make_field(numberOfTicks),
         make_field(whatToShow),
         make_field(useRth),
         make_field(ignoreSize)]

miscOptionsString = ""
if miscOptions:
    for tagValue in miscOptions:
        miscOptionsString += str(tagValue)
flds += [make_field(miscOptionsString),]
```

I didn't want to touch the api testing code too much because I believe @Tsopic is working on improvements to that here https://github.com/stoqey/ib/pull/87

Please let me know if any improvements are needed. It would be good to take a closer look at the API and see if the contract tokeniser could be shared between multiple API calls but that might not be possible.

2021-06-05 12:15 UTC, mfrener approved these changes
We use the Java client as a reference, but also there REQ_TICK_BY_TICK_DATA is not implemented by b.send(contract) (would be this.encodeContract(contract) for us), but they add send contract attributes one by one, as last two send's are actually different... https://github.com/stoqey/ib/blob/master/ref/client/EClient.java
So your fix is correct and in-line with the Java client code - thanks & approved ;)

2021-06-05 13:35 UTC, mfrener commented
I have found one more issue on the HISTORICAL_TICKS decoder (unprocessed data left on queue).
Will do a follow-up PR containing that fix, as well adding support for historical tick data to IBApiNext (+IBApiNext.getHistoricalTicksMid +IBApiNext.getHistoricalTicksBidAsk +IBApiNext.getHistoricalTicksLast)

2021-06-05 14:03 UTC, mfrener commented
Here it is https://github.com/stoqey/ib/pull/89

2021-06-07 12:17 UTC, Tsopic requested changes

2021-06-07 12:17 UTC, Tsopic commented on src/tests/unit/api/api.test.ts
> +      port: TEST_SERVER_POST,
Once the test env PR is merged

The only valid values are `IB_HOST` and `IB_PORT`

2021-06-07 12:18 UTC, Tsopic commented
Let us merge the other pr before, then I can change these values noted above myself to save you from the trouble ;)

2021-06-07 12:24 UTC, ant-fx commented
@Tsopic sounds good!

2021-06-08 09:42 UTC, Tsopic approved these changes

2021-06-08 09:43 UTC, Tsopic commented
@ant-fx merging this pr after tests pass

2021-06-08 09:45 UTC, merged